tools:
  external_code_coverage:
    timeout: 600
checks:
  php:
    code_rating: true
    duplication: true
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
