tools:
  external_code_coverage:
    timeout: 600
checks:
  php:
    code_rating: true
    duplication: true
build:
  dependencies:
    override:
      - composer install --no-interaction --no-scripts --ignore-platform-reqs
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
