language: php

branches:
  only:
    - /.*/

php:
  - 7
  - 7.1
  - 7.2

before_install:
  - phpenv config-add data/infra/travis-php/memcached.ini
  - phpenv config-add data/infra/travis-php/apcu.ini

before_script:
  - composer self-update
  - composer install --no-interaction
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]] || [[ $TRAVIS_PHP_VERSION = 7.2 ]]; then composer global require --dev phpstan/phpstan:0.9.*; fi

script:
  - mkdir build
  - composer check
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]] || [[ $TRAVIS_PHP_VERSION = 7.2 ]]; then ~/.composer/vendor/bin/phpstan analyse module/*/src/ --level=5; fi

after_script:
  - vendor/bin/phpcov merge build --clover build/clover.xml
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml

sudo: false
